"""added flask activities model

Revision ID: fb703b5c1583
Revises: 
Create Date: 2023-01-24 10:46:32.241491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb703b5c1583'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('participants', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('accessibility', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity'),
    sa.UniqueConstraint('price')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    # ### end Alembic commands ###
